Eliminate column
Helsinki-Qubits/qiskit-terra pull request #11
Opened 2022-10-15 08:42 UTC by jova486

Two test and body for method eliminate_column added. It may be necessary to add more tests later .

2022-10-17 12:49 UTC, seirepo requested changes

2022-10-17 13:05 UTC, jova486 commented on test/python/transpiler/test_permrowcol.py
> +        self.assertEqual(ret.all(), np.array([1, 0]).all())
It would be easier to return just list. I will change this.

2022-10-17 13:05 UTC, jova486 commented on test/python/transpiler/test_permrowcol.py
> +        self.assertEqual(1, sum(parity_mat[:, column]))
Ok.

2022-10-19 09:29 UTC, Alex-Elias approved these changes

2022-10-19 17:41 UTC, merged